/* SPDX-License-Identifier: Apache-2.0
 *
 * BlockBerry runtime: the Berry-side library that code generated by the
 * BlockBerry editor (blockberry-editor/src/berry_generator.ts) calls into:
 *
 *   sps.every(ms, fn), sps.wait(ms), sps.input(ch), sps.output(ch, v)
 *   sensor.ready(), sensor.temp()
 *   escalation.raise_if(id, cond, level, msg, cooldown)
 *   signal.set(name, state)
 *   monitor.record(metric, value, unit)
 *   log.print(msg)
 *
 * Channels are plain string parameters. Board specifics are resolved here:
 *   "LED0".."LED2"      user LEDs
 *   "SW0".."SW2"        user buttons (boards with gpio-keys)
 *   "JOY_UP" etc.       joystick (boards with adc-keys)
 *   "D0".."D15"         Arduino R3 header pins (board-specific map)
 *   "PA0".."PH15"       any GPIO by port/pin
 *
 * The cyclic tasks registered with sps.every() are driven by _bb_tick(),
 * which the REPL thread calls whenever it is idle waiting for input.
 */
#include <zephyr/kernel.h>
#include <zephyr/devicetree.h>
#include <zephyr/logging/log.h>

#include "berry.h"
#include "bb_runtime.h"

LOG_MODULE_REGISTER(bb_runtime, CONFIG_LOG_DEFAULT_LEVEL);

static const char bb_runtime_be[] =
	"import string\n"
	"_bb_tasks = []\n"
	"_bb_esc = {}\n"
	"_bb_sig = {}\n"
	"_bb_cfg = {}\n"
	"_bb_cur = nil\n"
	/* "PA5" -> ['a', 5] */
	"def _bb_pin(ch)\n"
	"  if size(ch) < 3 return nil end\n"
	"  var s = string.toupper(ch)\n"
	"  if s[0] != 'P' return nil end\n"
	"  var p = s[1]\n"
	"  if p < 'A' || p > 'H' return nil end\n"
	"  var pin = 0\n"
	"  var i = 2\n"
	"  while i < size(s)\n"
	"    var c = string.byte(s[i])\n"
	"    if c < 0x30 || c > 0x39 return nil end\n"
	"    pin = pin * 10 + (c - 0x30)\n"
	"    i += 1\n"
	"  end\n"
	"  if pin > 15 return nil end\n"
	"  return [string.tolower(p), pin]\n"
	"end\n"
	/* Arduino R3 header map (board-specific) */
	"_bb_dmap = {"
#if defined(CONFIG_BOARD_STM32WBA65I_DK1)
	"'D0':['a',11],'D1':['a',12],'D2':['e',0],'D3':['b',13],"
	"'D4':['a',3],'D5':['b',14],'D6':['b',0],'D7':['d',14],"
	"'D8':['a',10],'D9':['b',11],'D10':['b',9],'D11':['c',3],"
	"'D12':['a',9],'D13':['b',10],'D14':['b',1],'D15':['b',2]"
#endif
	"}\n"
	"def _bb_gpio(ch)\n"
	"  var pp = _bb_dmap.find(string.toupper(ch))\n"
	"  if pp == nil pp = _bb_pin(ch) end\n"
	"  return pp\n"
	"end\n"
	/* digital input by channel name */
	"def _bb_din(ch)\n"
	"  ch = str(ch)\n"
#ifdef CONFIG_INPUT
	"  if ch == 'JOY_UP' return joy() == 'up' end\n"
	"  if ch == 'JOY_DOWN' return joy() == 'down' end\n"
	"  if ch == 'JOY_LEFT' return joy() == 'left' end\n"
	"  if ch == 'JOY_RIGHT' return joy() == 'right' end\n"
	"  if ch == 'JOY_SELECT' return joy() == 'enter' end\n"
#endif
#if DT_NODE_EXISTS(DT_ALIAS(sw0))
	"  if ch == 'SW0' return button(0) != 0 end\n"
#endif
#if DT_NODE_EXISTS(DT_ALIAS(sw1))
	"  if ch == 'SW1' return button(1) != 0 end\n"
#endif
#if DT_NODE_EXISTS(DT_ALIAS(sw2))
	"  if ch == 'SW2' return button(2) != 0 end\n"
#endif
	"  var pp = _bb_gpio(ch)\n"
	"  if pp == nil raise 'value_error', 'unknown input channel: ' + ch end\n"
	"  if _bb_cfg.find(ch) == nil\n"
	"    pinmode(pp[0], pp[1], 'in_pu')\n"
	"    _bb_cfg[ch] = true\n"
	"  end\n"
	"  return dread(pp[0], pp[1]) != 0\n"
	"end\n"
	/* digital output by channel name */
	"def _bb_dout(ch, v)\n"
	"  ch = str(ch)\n"
	"  v = bool(v)\n"
#if DT_NODE_EXISTS(DT_ALIAS(led0))
	"  if ch == 'LED0' led(0, v) return end\n"
#endif
#if DT_NODE_EXISTS(DT_ALIAS(led1))
	"  if ch == 'LED1' led(1, v) return end\n"
#endif
#if DT_NODE_EXISTS(DT_ALIAS(led2))
	"  if ch == 'LED2' led(2, v) return end\n"
#endif
	"  var pp = _bb_gpio(ch)\n"
	"  if pp == nil raise 'value_error', 'unknown output channel: ' + ch end\n"
	"  if _bb_cfg.find(ch) == nil\n"
	"    pinmode(pp[0], pp[1], 'out')\n"
	"    _bb_cfg[ch] = true\n"
	"  end\n"
	"  dwrite(pp[0], pp[1], v)\n"
	"end\n"
	/* --- log --- */
	"log = module('log')\n"
	"log.print = def (msg) print('[log] ' + str(msg)) end\n"
	/* --- sps: cyclic mini PLC --- */
	"sps = module('sps')\n"
	"sps.every = def (interval, fn)\n"
	"  _bb_tasks.push({'i': int(interval), 'fn': fn, 'next': millis(), 'sleep': millis()})\n"
	"end\n"
	"sps.wait = def (ms)\n"
	"  if _bb_cur != nil\n"
	"    _bb_cur['sleep'] = millis() + int(ms)\n"
	"    raise 'bb_wait'\n"
	"  end\n"
	"end\n"
	"sps.input = def (ch) return _bb_din(ch) end\n"
	"sps.output = def (ch, v) _bb_dout(ch, v) end\n"
	"sps.clear = def () _bb_tasks = [] end\n"
	"def _bb_tick()\n"
	"  var now = millis()\n"
	"  for t: _bb_tasks\n"
	"    if now - t['next'] >= 0 && now - t['sleep'] >= 0\n"
	"      t['next'] = now + t['i']\n"
	"      _bb_cur = t\n"
	"      try\n"
	"        t['fn']()\n"
	"      except 'bb_wait'\n"
	"      except .. as e, m\n"
	"        log.print('task error: ' + str(e) + ': ' + str(m))\n"
	"      end\n"
	"      _bb_cur = nil\n"
	"    end\n"
	"  end\n"
	"end\n"
	/* --- sensor: die temperature --- */
	"sensor = module('sensor')\n"
#if defined(CONFIG_SENSOR) && DT_NODE_EXISTS(DT_ALIAS(die_temp0))
	"sensor.ready = def ()\n"
	"  try\n"
	"    temp()\n"
	"    return true\n"
	"  except ..\n"
	"    return false\n"
	"  end\n"
	"end\n"
	"sensor.temp = def () return temp() end\n"
#else
	"sensor.ready = def () return false end\n"
	"sensor.temp = def () raise 'io_error', 'no temperature sensor' end\n"
#endif
	/* --- signal: named states mapped to the user LEDs --- */
	"signal = module('signal')\n"
	"signal.set = def (name, state)\n"
	"  _bb_sig[str(name)] = str(state)\n"
	"  var g = state == 'normal'\n"
	"  var r = state == 'warning' || state == 'alarm'\n"
#if DT_NODE_EXISTS(DT_ALIAS(led0))
	"  led(0, g)\n"
#endif
#if DT_NODE_EXISTS(DT_ALIAS(led1))
	"  led(1, r)\n"
#endif
	"  if !g && !r && state != 'off'\n"
	"    log.print('signal ' + str(name) + ' -> ' + str(state))\n"
	"  end\n"
	"end\n"
	"signal.get = def (name) return _bb_sig.find(str(name)) end\n"
	/* --- monitor: measurement log --- */
	"monitor = module('monitor')\n"
	"monitor.record = def (metric, value, unit)\n"
	"  log.print(str(metric) + ' = ' + str(value) + ' ' + str(unit))\n"
	"end\n"
	/* --- escalation: stateful alarms with cooldown --- */
	"escalation = module('escalation')\n"
	"escalation.raise_if = def (id, cond, level, msg, cooldown)\n"
	"  var e = _bb_esc.find(id)\n"
	"  if e == nil\n"
	"    e = {'active': false, 'last': nil}\n"
	"    _bb_esc[id] = e\n"
	"  end\n"
	"  if !cond\n"
	"    e['active'] = false\n"
	"    return false\n"
	"  end\n"
	"  if e['active'] return false end\n"
	"  var now = millis()\n"
	"  if e['last'] != nil && now - e['last'] < int(cooldown) * 1000\n"
	"    return false\n"
	"  end\n"
	"  e['active'] = true\n"
	"  e['last'] = now\n"
	"  log.print('[' + str(level) + '] ' + str(msg))\n"
	"  return true\n"
	"end\n";

int bb_runtime_load(bvm *vm)
{
	if (be_loadbuffer(vm, "bb_runtime", bb_runtime_be,
			  sizeof(bb_runtime_be) - 1) != 0) {
		LOG_ERR("BlockBerry runtime failed to compile");
		be_dumpexcept(vm);
		return -EINVAL;
	}
	if (be_pcall(vm, 0) != 0) {
		LOG_ERR("BlockBerry runtime failed to run");
		be_dumpexcept(vm);
		be_pop(vm, 1);
		return -EINVAL;
	}
	be_pop(vm, 1);
	return 0;
}

void bb_runtime_tick(bvm *vm)
{
	static bool in_tick;

	if (vm == NULL || in_tick) {
		return;
	}
	in_tick = true;

	be_getglobal(vm, "_bb_tick");
	if (be_isfunction(vm, -1)) {
		if (be_pcall(vm, 0) != 0) {
			be_dumpexcept(vm);
		}
	}
	be_pop(vm, 1);

	in_tick = false;
}
